### PR TITLE
TR language added

### PR DESCRIPTION
**Pull request by calculous**
I added Turkish language for HeliPort App

### CODE REVIEW

**Comment by mehmetyukcell** [comment]
> I added Turkish language for HeliPort App

Çok Teşekkürler... Bu çok iyi bir haber.

**Comment by Aldo97** [comment]
I think you made something wrong because you modify too much files related to pods etc.
If you want I can add your commit to mine.

**Comment by calculous** [comment]
> I think you made something wrong because you modify too much files related to pods etc.
> If you want I can add your commit to mine.

Okay, It is my first time using XCode with pods. You could transfer changes to your commit. Thank you.

**Comment by Aldo97** [comment]
> > I think you made something wrong because you modify too much files related to pods etc.
> > If you want I can add your commit to mine.
> 
> Okay, It is my first time using XCode with pods. You could transfer changes to your commit. Thank you.
Made it, you can close this pull request.
You're welcome.

**Comment by calculous** [comment]
Thank you.

**Comment by williambj1** [comment]
Moved to #48

**Pull request closed without merging**
