### PR TITLE
Add French language

### PR DESCRIPTION
**Pull request by KikiManjaro**

### CODE REVIEW

**Comment by williambj1** [comment]
Please specify line ending and file encoding. Other than that, everything looks good. Thank you for your contribution!

**Comment by KikiManjaro** [comment]
Thank you, done :)

**Comment by DavidBuddy** [comment]
translation
Capture d’écran 2020-07-15 à 07 56 55
Capture d’écran 2020-07-15 à 07 56 18

**Comment by DavidBuddy** [comment]
Capture d’écran 2020-07-15 à 08 07 29
Capture d’écran 2020-07-15 à 08 05 55

**Pull request merged**
