### PR TITLE
Added Preference Panel to edit saved WiFi Networks

### PR DESCRIPTION
**Pull request by ErrorErrorError**
Hey!

I added the ability to view saved networks, view credentials, change priority, auto-join , and remove saved networks, as well as a Preference Panel so we can add other settings in the future, e.g. General. As of right now in order to access it you have to click `Open Network Preferences`.

I also simplified StatusMenu's Localization.

Also, is there a way to prevent multiple password requests from Keychain when viewing saved networks? Looks like "updating" the app as release asks for the password of the computer, which if you have a lot of Wi-Fi networks saved, it wouldn't be ideal to keep putting password on all those networks.

Ready for review!

### CODE REVIEW

**Comment by williambj1** [comment]
I'm quite busy these days. I may not be able to review and test the code until April 16.

**Huge thanks for your hard work!!!**

**Comment by 0fisher** [comment]
干的漂亮， 正好缺少这个功能

**Comment by igorkulman** [comment]
Trying it out now, in the networks list at the bottom lest there is a plus button. Is it supposed to do something? Because it is always disabled for me.

Screenshot 2020-08-07 at 15 30 10

**Comment by ErrorErrorError** [comment]
> Trying it out now, in the networks list at the bottom lest there is a plus button. Is it supposed to do something? Because it is always disabled for me.
> 
> 
> 
> Screenshot 2020-08-07 at 15 30 10
> 
> 

I was planning to allow adding new networks to be saved but I'm thinking of removing that plus button

**Comment by ErrorErrorError** [comment]
I will refactor WiFi popup into one class since there are currently 3 windows with the same purpose. Or just make another pull request?

**Comment by williambj1** [comment]
> Or just make another pull request?

Yes, that would be much better!

Merged, thanks!

**Pull request merged**
