### PR TITLE
Update Portuguese (Portugal) strings

### PR DESCRIPTION
**Pull request by RGarrido03**
Hi!
I updated the Portuguese (Portugal) string with the changes occurred with last commit (`f11d8ed`). Eat some Pasteis de Nata :P
Thank you so much!

### CODE REVIEW

**Comment by ErrorErrorError** [comment]
Is the `"none"` translation fixed? If so, please remove the `// FIXME` portion of the line. Thank you!

**Comment by RGarrido03** [comment]
Oops, yes it is, I'm sorry. I'll fix that tomorrow asap. Also, I have seen that ```none``` translation shouldn't be capitalized (and I capitalized it). Really sorry

**Comment by ErrorErrorError** [comment]
> Also, I have seen that `none` translation shouldn't be capitalized (and I capitalized it). Really sorry

Not sure why is the keyword `none` in there. `None` is supposed to be there since it's part of the security options, but `none` has nothing to do with localized strings.

**Comment by RGarrido03** [comment]
Well in fact I don't really know about that, I'm really noob at programming 😅

**Comment by RGarrido03** [comment]
Okay, fixed the //FIXME problem. Sorry!

**Pull request merged**
