### PR TITLE
Fixed issue where long ssid's were not being saved in keychain

### PR DESCRIPTION
**Pull request by ErrorErrorError**
This fixes issue https://github.com/OpenIntelWireless/HeliPort/issues/189.

It also fixes rare issue when random characters would appear if `ssid.count == 32`.

### CODE REVIEW

**Review by williambj1 — APPROVED** [review]

**Comment by williambj1** [comment]
Will merge once @masnormen confirms it works.

**Comment by masnormen** [comment]
Hello, I tried to run the built binary in #189 
I deleted the previous .app and then extracted the newly built app. But when I open it shows "HeliPort Running At An Unexpected Path", which is strange because I already placed it from the Applications folder.

Any idea why this happen?

**Comment by masnormen** [comment]
Update: turns out the problem is the archive manager. Now it runs.

It's working*. It now adds the password to keychain.

image

*) However, there is another problem. I can only join the network using the "Join Other Network" menu. It keeps scanning and not finding my network. I waited for like half an hour but it still keeps scanning for my network. But, it can find my network easily if I renamed it to a shorter name.

Should I open a new issue, or is this related to this PR?

**Review by Goshin — APPROVED** [review]

**Comment by ErrorErrorError** [comment]
> Update: turns out the problem is the archive manager. Now it runs.
> 
> 
> 
> It's working*. It now adds the password to keychain.
> 
> 
> 
> image
> 
> 
> 
> *) However, there is another problem. I can only join the network using the "Join Other Network" menu. It keeps scanning and not finding my network. I waited for like half an hour but it still keeps scanning for my network. But, it can find my network easily if I renamed it to a shorter name.
> 
> 
> 
> Should I open a new issue, or is this related to this PR?

Hm, I always had that issue with long SSID name but it would eventually show up. I will check it out and see what's going on.

**Pull request merged**
