### PR TITLE
Update italian localization

### PR DESCRIPTION
**Pull request by alessiomatricardi**
Hi, i've updated the italian localization file. If i've miss something i will add asap.
@Aldo97 can u check if everything is "fluent"?

### CODE REVIEW

**Comment by Aldo97** [comment]
> Hi, i've updated the italian localization file. If i've miss something i will add asap.
> @Aldo97 can u check if everything is "fluent"?

It seems ok.
Are you Italian? 
Right now I can't check if "none" and "General" are translated correctly in gender and number, this evening I'll check in heliport if you're not a native speaker.
Morover I would change "Mostra le credenziali salvate...sul portachiavi" in "Mostra le credenziali salvate nel portachiavi...", sounds better to me. 
These days I'm in vacation in a remote place so I hadn't noticed the new lines, thanks for your contribution.

**Comment by alessiomatricardi** [comment]
> > Hi, i've updated the italian localization file. If i've miss something i will add asap.
> > @Aldo97 can u check if everything is "fluent"?
> 
> It seems ok.
> Are you Italian?
> Right now I can't check if "none" and "General" are translated correctly in gender and number, this evening I'll check in heliport if you're not a native speaker.
> Morover I would change "Mostra le credenziali salvate...sul portachiavi" in "Mostra le credenziali salvate nel portachiavi...", sounds better to me.
> These days I'm in vacation in a remote place so I hadn't noticed the new lines, thanks for your contribution.



> > Hi, i've updated the italian localization file. If i've miss something i will add asap.
> > @Aldo97 can u check if everything is "fluent"?
> 
> It seems ok.
> Are you Italian?
> Right now I can't check if "none" and "General" are translated correctly in gender and number, this evening I'll check in heliport if you're not a native speaker.
> Morover I would change "Mostra le credenziali salvate...sul portachiavi" in "Mostra le credenziali salvate nel portachiavi...", sounds better to me.
> These days I'm in vacation in a remote place so I hadn't noticed the new lines, thanks for your contribution.

Yes, i'm italian :) but italian language is so vast so sometimes it's difficult to find the right terms :')
For "none" i've copy-paste the "None" definition, while "General" is used in the new Network Preference window for the general settings and, according to my iphone settings app, "General" is translated to "Generali" instead of "Generale".
For the "Mostra..." sentences u are right, my fault :')

**Comment by williambj1** [comment]
@alessiomatricardi Thanks for your contribution, is this PR ready to merge?

**Comment by alessiomatricardi** [comment]
> @alessiomatricardi Thanks for your contribution, is this PR ready to merge?

I think yes!

**Comment by williambj1** [comment]
Thx, merged!

**Pull request merged**
